// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for ExecutionContext
func (s *ExecutionContext) Bomlok_GetValue(field string) any {
	switch field {
	case "template":
		return s.template
	case "macroDepth":
		return s.macroDepth
	case "Autoescape":
		return s.Autoescape
	case "Public":
		return s.Public
	case "Private":
		return s.Private
	case "Shared":
		return s.Shared
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for ExecutionContext
func (s *ExecutionContext) Bomlok_Fields() []string {
	return []string{
		"template",
		"macroDepth",
		"Autoescape",
		"Public",
		"Private",
		"Shared",
		
	}
}

