// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for Error
func (s *Error) Bomlok_GetValue(field string) any {
	switch field {
	case "Template":
		return s.Template
	case "Filename":
		return s.Filename
	case "Line":
		return s.Line
	case "Column":
		return s.Column
	case "Token":
		return s.Token
	case "Sender":
		return s.Sender
	case "OrigError":
		return s.OrigError
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for Error
func (s *Error) Bomlok_Fields() []string {
	return []string{
		"Template",
		"Filename",
		"Line",
		"Column",
		"Token",
		"Sender",
		"OrigError",
		
	}
}

