// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for filterCall
func (s *filterCall) Bomlok_GetValue(field string) any {
	switch field {
	case "token":
		return s.token
	case "name":
		return s.name
	case "parameter":
		return s.parameter
	case "filterFunc":
		return s.filterFunc
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for filterCall
func (s *filterCall) Bomlok_Fields() []string {
	return []string{
		"token",
		"name",
		"parameter",
		"filterFunc",
		
	}
}

