// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for Token
func (s *Token) Bomlok_GetValue(field string) any {
	switch field {
	case "Filename":
		return s.Filename
	case "Typ":
		return s.Typ
	case "Val":
		return s.Val
	case "Line":
		return s.Line
	case "Col":
		return s.Col
	case "TrimWhitespaces":
		return s.TrimWhitespaces
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for Token
func (s *Token) Bomlok_Fields() []string {
	return []string{
		"Filename",
		"Typ",
		"Val",
		"Line",
		"Col",
		"TrimWhitespaces",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for lexer
func (s *lexer) Bomlok_GetValue(field string) any {
	switch field {
	case "name":
		return s.name
	case "input":
		return s.input
	case "start":
		return s.start
	case "pos":
		return s.pos
	case "width":
		return s.width
	case "tokens":
		return s.tokens
	case "errored":
		return s.errored
	case "startline":
		return s.startline
	case "startcol":
		return s.startcol
	case "line":
		return s.line
	case "col":
		return s.col
	case "inVerbatim":
		return s.inVerbatim
	case "verbatimName":
		return s.verbatimName
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for lexer
func (s *lexer) Bomlok_Fields() []string {
	return []string{
		"name",
		"input",
		"start",
		"pos",
		"width",
		"tokens",
		"errored",
		"startline",
		"startcol",
		"line",
		"col",
		"inVerbatim",
		"verbatimName",
		
	}
}

