// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for nodeHTML
func (s *nodeHTML) Bomlok_GetValue(field string) any {
	switch field {
	case "token":
		return s.token
	case "trimLeft":
		return s.trimLeft
	case "trimRight":
		return s.trimRight
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for nodeHTML
func (s *nodeHTML) Bomlok_Fields() []string {
	return []string{
		"token",
		"trimLeft",
		"trimRight",
		
	}
}

