// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for nodeDocument
func (s *nodeDocument) Bomlok_GetValue(field string) any {
	switch field {
	case "Nodes":
		return s.Nodes
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for nodeDocument
func (s *nodeDocument) Bomlok_Fields() []string {
	return []string{
		"Nodes",
		
	}
}

