// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for NodeWrapper
func (s *NodeWrapper) Bomlok_GetValue(field string) any {
	switch field {
	case "Endtag":
		return s.Endtag
	case "nodes":
		return s.nodes
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for NodeWrapper
func (s *NodeWrapper) Bomlok_Fields() []string {
	return []string{
		"Endtag",
		"nodes",
		
	}
}

