// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for Options
func (s *Options) Bomlok_GetValue(field string) any {
	switch field {
	case "TrimBlocks":
		return s.TrimBlocks
	case "LStripBlocks":
		return s.LStripBlocks
	case "TrimWhitespace":
		return s.TrimWhitespace
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for Options
func (s *Options) Bomlok_Fields() []string {
	return []string{
		"TrimBlocks",
		"LStripBlocks",
		"TrimWhitespace",
		
	}
}

