// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for Parser
func (s *Parser) Bomlok_GetValue(field string) any {
	switch field {
	case "name":
		return s.name
	case "idx":
		return s.idx
	case "tokens":
		return s.tokens
	case "lastToken":
		return s.lastToken
	case "template":
		return s.template
	case "htmlInQuote":
		return s.htmlInQuote
	case "htmlLastChar":
		return s.htmlLastChar
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for Parser
func (s *Parser) Bomlok_Fields() []string {
	return []string{
		"name",
		"idx",
		"tokens",
		"lastToken",
		"template",
		"htmlInQuote",
		"htmlLastChar",
		
	}
}

