// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for Expression
func (s *Expression) Bomlok_GetValue(field string) any {
	switch field {
	case "expr1":
		return s.expr1
	case "expr2":
		return s.expr2
	case "opToken":
		return s.opToken
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for Expression
func (s *Expression) Bomlok_Fields() []string {
	return []string{
		"expr1",
		"expr2",
		"opToken",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for relationalExpression
func (s *relationalExpression) Bomlok_GetValue(field string) any {
	switch field {
	case "expr1":
		return s.expr1
	case "expr2":
		return s.expr2
	case "opToken":
		return s.opToken
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for relationalExpression
func (s *relationalExpression) Bomlok_Fields() []string {
	return []string{
		"expr1",
		"expr2",
		"opToken",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for simpleExpression
func (s *simpleExpression) Bomlok_GetValue(field string) any {
	switch field {
	case "negate":
		return s.negate
	case "negativeSign":
		return s.negativeSign
	case "term1":
		return s.term1
	case "term2":
		return s.term2
	case "opToken":
		return s.opToken
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for simpleExpression
func (s *simpleExpression) Bomlok_Fields() []string {
	return []string{
		"negate",
		"negativeSign",
		"term1",
		"term2",
		"opToken",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for term
func (s *term) Bomlok_GetValue(field string) any {
	switch field {
	case "factor1":
		return s.factor1
	case "factor2":
		return s.factor2
	case "opToken":
		return s.opToken
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for term
func (s *term) Bomlok_Fields() []string {
	return []string{
		"factor1",
		"factor2",
		"opToken",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for power
func (s *power) Bomlok_GetValue(field string) any {
	switch field {
	case "power1":
		return s.power1
	case "power2":
		return s.power2
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for power
func (s *power) Bomlok_Fields() []string {
	return []string{
		"power1",
		"power2",
		
	}
}

