// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for tagCycleValue
func (s *tagCycleValue) Bomlok_GetValue(field string) any {
	switch field {
	case "node":
		return s.node
	case "value":
		return s.value
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagCycleValue
func (s *tagCycleValue) Bomlok_Fields() []string {
	return []string{
		"node",
		"value",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for tagCycleNode
func (s *tagCycleNode) Bomlok_GetValue(field string) any {
	switch field {
	case "position":
		return s.position
	case "args":
		return s.args
	case "idx":
		return s.idx
	case "asName":
		return s.asName
	case "silent":
		return s.silent
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagCycleNode
func (s *tagCycleNode) Bomlok_Fields() []string {
	return []string{
		"position",
		"args",
		"idx",
		"asName",
		"silent",
		
	}
}

