// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for tagIfchangedNode
func (s *tagIfchangedNode) Bomlok_GetValue(field string) any {
	switch field {
	case "watchedExpr":
		return s.watchedExpr
	case "lastValues":
		return s.lastValues
	case "lastContent":
		return s.lastContent
	case "thenWrapper":
		return s.thenWrapper
	case "elseWrapper":
		return s.elseWrapper
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagIfchangedNode
func (s *tagIfchangedNode) Bomlok_Fields() []string {
	return []string{
		"watchedExpr",
		"lastValues",
		"lastContent",
		"thenWrapper",
		"elseWrapper",
		
	}
}

