// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for tagMacroNode
func (s *tagMacroNode) Bomlok_GetValue(field string) any {
	switch field {
	case "position":
		return s.position
	case "name":
		return s.name
	case "argsOrder":
		return s.argsOrder
	case "args":
		return s.args
	case "exported":
		return s.exported
	case "wrapper":
		return s.wrapper
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagMacroNode
func (s *tagMacroNode) Bomlok_Fields() []string {
	return []string{
		"position",
		"name",
		"argsOrder",
		"args",
		"exported",
		"wrapper",
		
	}
}

