// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for tagIncludeNode
func (s *tagIncludeNode) Bomlok_GetValue(field string) any {
	switch field {
	case "tpl":
		return s.tpl
	case "filenameEvaluator":
		return s.filenameEvaluator
	case "lazy":
		return s.lazy
	case "only":
		return s.only
	case "filename":
		return s.filename
	case "withPairs":
		return s.withPairs
	case "ifExists":
		return s.ifExists
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagIncludeNode
func (s *tagIncludeNode) Bomlok_Fields() []string {
	return []string{
		"tpl",
		"filenameEvaluator",
		"lazy",
		"only",
		"filename",
		"withPairs",
		"ifExists",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for tagIncludeEmptyNode
func (s *tagIncludeEmptyNode) Bomlok_GetValue(field string) any {
	switch field {
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagIncludeEmptyNode
func (s *tagIncludeEmptyNode) Bomlok_Fields() []string {
	return []string{
		
	}
}

