// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for tagNowNode
func (s *tagNowNode) Bomlok_GetValue(field string) any {
	switch field {
	case "position":
		return s.position
	case "format":
		return s.format
	case "fake":
		return s.fake
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagNowNode
func (s *tagNowNode) Bomlok_Fields() []string {
	return []string{
		"position",
		"format",
		"fake",
		
	}
}

