// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for tagAutoescapeNode
func (s *tagAutoescapeNode) Bomlok_GetValue(field string) any {
	switch field {
	case "wrapper":
		return s.wrapper
	case "autoescape":
		return s.autoescape
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagAutoescapeNode
func (s *tagAutoescapeNode) Bomlok_Fields() []string {
	return []string{
		"wrapper",
		"autoescape",
		
	}
}

