// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for tagIfNode
func (s *tagIfNode) Bomlok_GetValue(field string) any {
	switch field {
	case "conditions":
		return s.conditions
	case "wrappers":
		return s.wrappers
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagIfNode
func (s *tagIfNode) Bomlok_Fields() []string {
	return []string{
		"conditions",
		"wrappers",
		
	}
}

