// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for tagCommentNode
func (s *tagCommentNode) Bomlok_GetValue(field string) any {
	switch field {
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagCommentNode
func (s *tagCommentNode) Bomlok_Fields() []string {
	return []string{
		
	}
}

