// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for nodeFilterCall
func (s *nodeFilterCall) Bomlok_GetValue(field string) any {
	switch field {
	case "name":
		return s.name
	case "paramExpr":
		return s.paramExpr
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for nodeFilterCall
func (s *nodeFilterCall) Bomlok_Fields() []string {
	return []string{
		"name",
		"paramExpr",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for tagFilterNode
func (s *tagFilterNode) Bomlok_GetValue(field string) any {
	switch field {
	case "position":
		return s.position
	case "bodyWrapper":
		return s.bodyWrapper
	case "filterChain":
		return s.filterChain
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagFilterNode
func (s *tagFilterNode) Bomlok_Fields() []string {
	return []string{
		"position",
		"bodyWrapper",
		"filterChain",
		
	}
}

