// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for tagSSINode
func (s *tagSSINode) Bomlok_GetValue(field string) any {
	switch field {
	case "filename":
		return s.filename
	case "content":
		return s.content
	case "template":
		return s.template
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagSSINode
func (s *tagSSINode) Bomlok_Fields() []string {
	return []string{
		"filename",
		"content",
		"template",
		
	}
}

