// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for tagSpacelessNode
func (s *tagSpacelessNode) Bomlok_GetValue(field string) any {
	switch field {
	case "wrapper":
		return s.wrapper
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagSpacelessNode
func (s *tagSpacelessNode) Bomlok_Fields() []string {
	return []string{
		"wrapper",
		
	}
}

