// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for tagIfEqualNode
func (s *tagIfEqualNode) Bomlok_GetValue(field string) any {
	switch field {
	case "var1":
		return s.var1
	case "var2":
		return s.var2
	case "thenWrapper":
		return s.thenWrapper
	case "elseWrapper":
		return s.elseWrapper
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagIfEqualNode
func (s *tagIfEqualNode) Bomlok_Fields() []string {
	return []string{
		"var1",
		"var2",
		"thenWrapper",
		"elseWrapper",
		
	}
}

