// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for tagBlockNode
func (s *tagBlockNode) Bomlok_GetValue(field string) any {
	switch field {
	case "name":
		return s.name
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagBlockNode
func (s *tagBlockNode) Bomlok_Fields() []string {
	return []string{
		"name",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for tagBlockInformation
func (s *tagBlockInformation) Bomlok_GetValue(field string) any {
	switch field {
	case "ctx":
		return s.ctx
	case "wrappers":
		return s.wrappers
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagBlockInformation
func (s *tagBlockInformation) Bomlok_Fields() []string {
	return []string{
		"ctx",
		"wrappers",
		
	}
}

