// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for tagImportNode
func (s *tagImportNode) Bomlok_GetValue(field string) any {
	switch field {
	case "position":
		return s.position
	case "filename":
		return s.filename
	case "macros":
		return s.macros
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagImportNode
func (s *tagImportNode) Bomlok_Fields() []string {
	return []string{
		"position",
		"filename",
		"macros",
		
	}
}

