// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for tagTemplateTagNode
func (s *tagTemplateTagNode) Bomlok_GetValue(field string) any {
	switch field {
	case "content":
		return s.content
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagTemplateTagNode
func (s *tagTemplateTagNode) Bomlok_Fields() []string {
	return []string{
		"content",
		
	}
}

