// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for tagSetNode
func (s *tagSetNode) Bomlok_GetValue(field string) any {
	switch field {
	case "name":
		return s.name
	case "expression":
		return s.expression
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagSetNode
func (s *tagSetNode) Bomlok_Fields() []string {
	return []string{
		"name",
		"expression",
		
	}
}

