// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for tagFirstofNode
func (s *tagFirstofNode) Bomlok_GetValue(field string) any {
	switch field {
	case "position":
		return s.position
	case "args":
		return s.args
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagFirstofNode
func (s *tagFirstofNode) Bomlok_Fields() []string {
	return []string{
		"position",
		"args",
		
	}
}

