// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for tag
func (s *tag) Bomlok_GetValue(field string) any {
	switch field {
	case "name":
		return s.name
	case "parser":
		return s.parser
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tag
func (s *tag) Bomlok_Fields() []string {
	return []string{
		"name",
		"parser",
		
	}
}

