// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for tagLoremNode
func (s *tagLoremNode) Bomlok_GetValue(field string) any {
	switch field {
	case "position":
		return s.position
	case "count":
		return s.count
	case "method":
		return s.method
	case "random":
		return s.random
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagLoremNode
func (s *tagLoremNode) Bomlok_Fields() []string {
	return []string{
		"position",
		"count",
		"method",
		"random",
		
	}
}

