// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for tagForNode
func (s *tagForNode) Bomlok_GetValue(field string) any {
	switch field {
	case "key":
		return s.key
	case "value":
		return s.value
	case "objectEvaluator":
		return s.objectEvaluator
	case "reversed":
		return s.reversed
	case "sorted":
		return s.sorted
	case "bodyWrapper":
		return s.bodyWrapper
	case "emptyWrapper":
		return s.emptyWrapper
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagForNode
func (s *tagForNode) Bomlok_Fields() []string {
	return []string{
		"key",
		"value",
		"objectEvaluator",
		"reversed",
		"sorted",
		"bodyWrapper",
		"emptyWrapper",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for tagForLoopInformation
func (s *tagForLoopInformation) Bomlok_GetValue(field string) any {
	switch field {
	case "Counter":
		return s.Counter
	case "Counter0":
		return s.Counter0
	case "Revcounter":
		return s.Revcounter
	case "Revcounter0":
		return s.Revcounter0
	case "First":
		return s.First
	case "Last":
		return s.Last
	case "Parentloop":
		return s.Parentloop
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagForLoopInformation
func (s *tagForLoopInformation) Bomlok_Fields() []string {
	return []string{
		"Counter",
		"Counter0",
		"Revcounter",
		"Revcounter0",
		"First",
		"Last",
		"Parentloop",
		
	}
}

