// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for tagExtendsNode
func (s *tagExtendsNode) Bomlok_GetValue(field string) any {
	switch field {
	case "filename":
		return s.filename
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagExtendsNode
func (s *tagExtendsNode) Bomlok_Fields() []string {
	return []string{
		"filename",
		
	}
}

