// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for tagWidthratioNode
func (s *tagWidthratioNode) Bomlok_GetValue(field string) any {
	switch field {
	case "position":
		return s.position
	case "current":
		return s.current
	case "max":
		return s.max
	case "width":
		return s.width
	case "ctxName":
		return s.ctxName
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagWidthratioNode
func (s *tagWidthratioNode) Bomlok_Fields() []string {
	return []string{
		"position",
		"current",
		"max",
		"width",
		"ctxName",
		
	}
}

