// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for tagWithNode
func (s *tagWithNode) Bomlok_GetValue(field string) any {
	switch field {
	case "withPairs":
		return s.withPairs
	case "wrapper":
		return s.wrapper
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for tagWithNode
func (s *tagWithNode) Bomlok_Fields() []string {
	return []string{
		"withPairs",
		"wrapper",
		
	}
}

