// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for TemplateSet
func (s *TemplateSet) Bomlok_GetValue(field string) any {
	switch field {
	case "name":
		return s.name
	case "loaders":
		return s.loaders
	case "Globals":
		return s.Globals
	case "Debug":
		return s.Debug
	case "Options":
		return s.Options
	case "firstTemplateCreated":
		return s.firstTemplateCreated
	case "bannedTags":
		return s.bannedTags
	case "bannedFilters":
		return s.bannedFilters
	case "templateCache":
		return s.templateCache
	case "templateCacheMutex":
		return s.templateCacheMutex
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for TemplateSet
func (s *TemplateSet) Bomlok_Fields() []string {
	return []string{
		"name",
		"loaders",
		"Globals",
		"Debug",
		"Options",
		"firstTemplateCreated",
		"bannedTags",
		"bannedFilters",
		"templateCache",
		"templateCacheMutex",
		
	}
}

