// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for FSLoader
func (s *FSLoader) Bomlok_GetValue(field string) any {
	switch field {
	case "fs":
		return s.fs
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for FSLoader
func (s *FSLoader) Bomlok_Fields() []string {
	return []string{
		"fs",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for LocalFilesystemLoader
func (s *LocalFilesystemLoader) Bomlok_GetValue(field string) any {
	switch field {
	case "baseDir":
		return s.baseDir
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for LocalFilesystemLoader
func (s *LocalFilesystemLoader) Bomlok_Fields() []string {
	return []string{
		"baseDir",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for SandboxedFilesystemLoader
func (s *SandboxedFilesystemLoader) Bomlok_GetValue(field string) any {
	switch field {
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for SandboxedFilesystemLoader
func (s *SandboxedFilesystemLoader) Bomlok_Fields() []string {
	return []string{
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for HttpFilesystemLoader
func (s *HttpFilesystemLoader) Bomlok_GetValue(field string) any {
	switch field {
	case "fs":
		return s.fs
	case "baseDir":
		return s.baseDir
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for HttpFilesystemLoader
func (s *HttpFilesystemLoader) Bomlok_Fields() []string {
	return []string{
		"fs",
		"baseDir",
		
	}
}

