// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for templateWriter
func (s *templateWriter) Bomlok_GetValue(field string) any {
	switch field {
	case "w":
		return s.w
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for templateWriter
func (s *templateWriter) Bomlok_Fields() []string {
	return []string{
		"w",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for Template
func (s *Template) Bomlok_GetValue(field string) any {
	switch field {
	case "set":
		return s.set
	case "isTplString":
		return s.isTplString
	case "name":
		return s.name
	case "tpl":
		return s.tpl
	case "size":
		return s.size
	case "tokens":
		return s.tokens
	case "parser":
		return s.parser
	case "level":
		return s.level
	case "parent":
		return s.parent
	case "child":
		return s.child
	case "blocks":
		return s.blocks
	case "exportedMacros":
		return s.exportedMacros
	case "root":
		return s.root
	case "Options":
		return s.Options
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for Template
func (s *Template) Bomlok_Fields() []string {
	return []string{
		"set",
		"isTplString",
		"name",
		"tpl",
		"size",
		"tokens",
		"parser",
		"level",
		"parent",
		"child",
		"blocks",
		"exportedMacros",
		"root",
		"Options",
		
	}
}

