// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for Value
func (s *Value) Bomlok_GetValue(field string) any {
	switch field {
	case "val":
		return s.val
	case "safe":
		return s.safe
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for Value
func (s *Value) Bomlok_Fields() []string {
	return []string{
		"val",
		"safe",
		
	}
}

