// Code generated by bomlok. DO NOT EDIT.

package pongo2


// Bomlok_GetValue returns the value of the field with the given name for variablePart
func (s *variablePart) Bomlok_GetValue(field string) any {
	switch field {
	case "typ":
		return s.typ
	case "s":
		return s.s
	case "i":
		return s.i
	case "subscript":
		return s.subscript
	case "isNil":
		return s.isNil
	case "isFunctionCall":
		return s.isFunctionCall
	case "callingArgs":
		return s.callingArgs
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for variablePart
func (s *variablePart) Bomlok_Fields() []string {
	return []string{
		"typ",
		"s",
		"i",
		"subscript",
		"isNil",
		"isFunctionCall",
		"callingArgs",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for stringResolver
func (s *stringResolver) Bomlok_GetValue(field string) any {
	switch field {
	case "locationToken":
		return s.locationToken
	case "val":
		return s.val
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for stringResolver
func (s *stringResolver) Bomlok_Fields() []string {
	return []string{
		"locationToken",
		"val",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for intResolver
func (s *intResolver) Bomlok_GetValue(field string) any {
	switch field {
	case "locationToken":
		return s.locationToken
	case "val":
		return s.val
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for intResolver
func (s *intResolver) Bomlok_Fields() []string {
	return []string{
		"locationToken",
		"val",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for floatResolver
func (s *floatResolver) Bomlok_GetValue(field string) any {
	switch field {
	case "locationToken":
		return s.locationToken
	case "val":
		return s.val
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for floatResolver
func (s *floatResolver) Bomlok_Fields() []string {
	return []string{
		"locationToken",
		"val",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for boolResolver
func (s *boolResolver) Bomlok_GetValue(field string) any {
	switch field {
	case "locationToken":
		return s.locationToken
	case "val":
		return s.val
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for boolResolver
func (s *boolResolver) Bomlok_Fields() []string {
	return []string{
		"locationToken",
		"val",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for variableResolver
func (s *variableResolver) Bomlok_GetValue(field string) any {
	switch field {
	case "locationToken":
		return s.locationToken
	case "parts":
		return s.parts
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for variableResolver
func (s *variableResolver) Bomlok_Fields() []string {
	return []string{
		"locationToken",
		"parts",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for nodeFilteredVariable
func (s *nodeFilteredVariable) Bomlok_GetValue(field string) any {
	switch field {
	case "locationToken":
		return s.locationToken
	case "resolver":
		return s.resolver
	case "filterChain":
		return s.filterChain
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for nodeFilteredVariable
func (s *nodeFilteredVariable) Bomlok_Fields() []string {
	return []string{
		"locationToken",
		"resolver",
		"filterChain",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for nodeVariable
func (s *nodeVariable) Bomlok_GetValue(field string) any {
	switch field {
	case "locationToken":
		return s.locationToken
	case "expr":
		return s.expr
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for nodeVariable
func (s *nodeVariable) Bomlok_Fields() []string {
	return []string{
		"locationToken",
		"expr",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for executionCtxEval
func (s *executionCtxEval) Bomlok_GetValue(field string) any {
	switch field {
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for executionCtxEval
func (s *executionCtxEval) Bomlok_Fields() []string {
	return []string{
		
	}
}

